# Site settings
title:       Jornada
email:       familiajornada@gmail.com
description: "Ser pai e mãe é muito gostoso"
baseurl:     ""
url:         "http://jornadablog.github.io"
date_format: "%b %-d, %Y"

authors:
  gstv:
    display_name: Gustavo Nering
    avatar: gstv.png
  stheff:
    display_name: Stheffany Nering
    avatar: stheff.png

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     1
sass:
  compressed: true
